/**
 * init command - Initialize a new wiki directory
 *
 * Creates the wiki directory structure:
 * - wiki/ (root for markdown pages)
 * - projects/ (for project-scoped notes)
 * - .local/ (state, search index)
 * - .config/ (shared settings)
 *
 * Also initializes git repo and creates default config.
 */
import { Command } from 'commander';
import path from 'node:path';
import { homedir } from 'node:os';
import { access, constants } from 'node:fs/promises';
import { FsFileStore } from '@ivkond-llm-wiki/infra';
import { simpleGit, type SimpleGit } from 'simple-git';

async function dirExists(p: string): Promise<boolean> {
  try {
    await access(p, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function checkWikiExists(wikiPath: string): Promise<boolean> {
  const configDir = path.join(wikiPath, '.config');
  const localDir = path.join(wikiPath, '.local');
  return (await dirExists(configDir)) || (await dirExists(localDir));
}

async function initGitRepo(repoRoot: string): Promise<void> {
  const git: SimpleGit = simpleGit(repoRoot);
  await git.init();
  // Create initial commit if needed
  const status = await git.status();
  if (!status.isClean()) {
    await git.add('.');
    await git.commit('Initial commit');
  }
}

function hasGitIdentityEnv(): boolean {
  const authorName = process.env.GIT_AUTHOR_NAME?.trim();
  const authorEmail = process.env.GIT_AUTHOR_EMAIL?.trim();
  const committerName = process.env.GIT_COMMITTER_NAME?.trim();
  const committerEmail = process.env.GIT_COMMITTER_EMAIL?.trim();
  return Boolean(
    (authorName && authorEmail) ||
    (committerName && committerEmail) ||
    (authorName && committerEmail) ||
    (committerName && authorEmail),
  );
}

async function ensureGitIdentity(repoRoot: string): Promise<void> {
  if (hasGitIdentityEnv()) return;

  const git: SimpleGit = simpleGit(repoRoot);
  const [name, email] = await Promise.all([
    git.raw(['config', '--get', 'user.name']),
    git.raw(['config', '--get', 'user.email']),
  ]);
  const configuredName = name.trim();
  const configuredEmail = email.trim();

  if (configuredName && configuredEmail) return;

  throw new Error(
    'Git author identity is not configured. Set it with:\n' +
      '  git config --global user.name "Your Name"\n' +
      '  git config --global user.email "you@example.com"\n' +
      'Or set GIT_AUTHOR_* / GIT_COMMITTER_* environment variables for automation.',
  );
}

export const initCommand = new Command()
  .name('init')
  .description('Initialize a new wiki directory')
  .option('-f, --force', 'Overwrite existing wiki directory', false)
  .argument('[directory]', 'Wiki directory path (default: ~/.llm-wiki)')
  .action(async (directory: string | undefined, options: { force?: boolean }) => {
    const wikiPath = directory ? path.resolve(directory) : path.join(homedir(), '.llm-wiki');
    const force = options.force ?? false;

    // Check if wiki already exists
    if (!force && (await checkWikiExists(wikiPath))) {
      console.error(`Wiki already exists at ${wikiPath}`);
      console.error('Use --force to overwrite, or choose a different directory');
      process.exit(1);
    }

    console.log(`Initializing wiki at: ${wikiPath}`);

    try {
      // Use FsFileStore for file operations (with root = wikiPath)
      const fileStore = new FsFileStore(wikiPath);

      // Create directory structure through writeFile (creates parent dirs)
      await fileStore.writeFile('wiki/.gitkeep', '');
      await fileStore.writeFile('projects/.gitkeep', '');

      // Ensure .local and .config directories exist by writing placeholder files
      // The fileStore.writeFile will create parent directories automatically
      await fileStore.writeFile('.local/.gitkeep', '');

      // Create default config
      const configContent = `# LLM Wiki Configuration
# Generated by llm-wiki init

wiki:
  path: ${wikiPath}

llm:
  provider: openai
  model: gpt-4o-mini
  # api_key: your-key-here

embedding:
  provider: openai
  model: text-embedding-3-small
  # api_key: your-key-here

search:
  db_path: .local/search.db
  rerank: false
  cascade_threshold: 0.3

git:
  auto_commit: true
  squash_on_lint: true
  worktree_for_lint: true

consolidation:
  batch_threshold: 10
  archive_after_days: 30
  archive_retention_months: 6

sanitization:
  enabled: true
  mode: redact
  custom_patterns: []
  allowlist: []

mcp:
  host: 127.0.0.1
  port: 7849

imports:
  claude-code:
    enabled: true
    paths:
      - ~/.claude/projects/*/memory/*.md
  kiro:
    enabled: true
    paths:
      - .kiro/steering/**/*.md
`;

      await fileStore.writeFile('.config/settings.shared.yaml', configContent);

      await ensureGitIdentity(wikiPath);

      // Initialize git repository
      await initGitRepo(wikiPath);

      console.log('\x1b[32m%s\x1b[0m', '✓ Wiki initialized successfully!');
      console.log(`  - Wiki root: ${wikiPath}`);
      console.log(`  - Pages: ${path.join(wikiPath, 'wiki')}`);
      console.log(`  - Projects: ${path.join(wikiPath, 'projects')}`);
      console.log(`  - Config: ${path.join(wikiPath, '.config', 'settings.shared.yaml')}`);
      console.log(`  - Git repository: ${wikiPath}`);

      console.log('\nTo configure, edit:');
      console.log(`  ${path.join(wikiPath, '.config', 'settings.shared.yaml')}`);
      console.log('\nOr set environment variables:');
      console.log('  LLM_WIKI_LLM_API_KEY=your-key-here');
      console.log('  LLM_WIKI_EMBEDDING_API_KEY=your-key-here');
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`\x1b[31m%s\x1b[0m`, `Failed to initialize wiki: ${message}`);
      process.exit(1);
    }
  })
  .addHelpText(
    'after',
    `

Examples:
  llm-wiki init                  Initialize in ~/.llm-wiki
  llm-wiki init ./my-wiki        Initialize in current directory
  llm-wiki init --force ./wiki   Force overwrite existing`,
  );
