/**
 * init command - Initialize a new wiki directory
 *
 * Creates the wiki directory structure:
 * - wiki/ (root for markdown pages)
 * - projects/ (for project-scoped notes)
 * - .local/ (state, search index)
 * - .config/ (shared settings)
 */
import { Command } from 'commander';
import path from 'node:path';
import { homedir } from 'node:os';
import { mkdir, writeFile } from 'node:fs/promises';

export const initCommand = new Command()
  .name('init')
  .description('Initialize a new wiki directory')
  .option('-f, --force', 'Overwrite existing wiki directory', false)
  .argument('[directory]', 'Wiki directory path (default: ~/.llm-wiki)')
  .action(async (directory: string | undefined, _options: { force?: boolean }) => {
    const wikiPath = directory ? path.resolve(directory) : path.join(homedir(), '.llm-wiki');
    // Note: --force option available for future use (overwrite behavior)

    console.log(`Initializing wiki at: ${wikiPath}`);

    try {
      // Create directory structure
      const dirs = [
        path.join(wikiPath),
        path.join(wikiPath, 'wiki'),
        path.join(wikiPath, 'projects'),
        path.join(wikiPath, '.local'),
        path.join(wikiPath, '.local', 'search.db'),
        path.join(wikiPath, '.config'),
      ];

      for (const dir of dirs) {
        await mkdir(dir, { recursive: true });
      }

      // Create default config
      const configContent = `# LLM Wiki Configuration
# Generated by llm-wiki init

wiki:
  path: ${wikiPath}

llm:
  provider: openai
  model: gpt-4o-mini
  # api_key: your-key-here

embedding:
  provider: openai
  model: text-embedding-3-small
  # api_key: your-key-here

search:
  db_path: .local/search.db
  rerank: false
  cascade_threshold: 0.3

git:
  auto_commit: true
  squash_on_lint: true
  worktree_for_lint: true

consolidation:
  batch_threshold: 10
  archive_after_days: 30
  archive_retention_months: 6

sanitization:
  enabled: true
  mode: redact
  custom_patterns: []
  allowlist: []

mcp:
  host: 127.0.0.1
  port: 7849
`;

      await writeFile(path.join(wikiPath, '.config', 'settings.shared.yaml'), configContent);

      console.log('Wiki initialized successfully!');
      console.log(`  - Wiki root: ${wikiPath}`);
      console.log(`  - Pages: ${path.join(wikiPath, 'wiki')}`);
      console.log(`  - Projects: ${path.join(wikiPath, 'projects')}`);
      console.log(`  - Config: ${path.join(wikiPath, '.config', 'settings.shared.yaml')}`);
    } catch (error) {
      console.error(`Failed to initialize wiki: ${error}`);
      process.exit(1);
    }
  })
  .addHelpText(
    'after',
    `

Examples:
  llm-wiki init                  Initialize in ~/.llm-wiki
  llm-wiki init ./my-wiki        Initialize in current directory
  llm-wiki init --force ./wiki   Force overwrite existing`,
  );
